service: ${self:custom.stages.environment.${self:provider.stage}.service}

custom: ${file(./conf/custom.yml)}

plugins:
  - serverless-plugin-common-excludes
  - serverless-plugin-include-dependencies
  - '@anttiviljami/serverless-stack-output'
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-prune-plugin

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, self:custom.defaultStage}
  region: ${opt:region, "${self:custom.stages.environment.${self:provider.stage}.region}"}
  stackName: ${self:custom.stages.environment.${self:provider.stage}.stackName}
  apiGateway: ${self:custom.stages.environment.${self:provider.stage}.apiGateway}
  environment:
    NODE_ENV: ${opt:stage, self:custom.defaultStage}
    API_VERSION: ${opt:apiver, env:VERSION, file(${self:custom.confDir}/${self:custom.shareYml}):version}
    TZ: ${self:custom.stages.environment.${self:provider.stage}.timezone}
    CONNECTIONS_TABLE:
      Ref: ConnectionsTable
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DeleteItem
        - dynamodb:GetItem
        - dynamodb:Scan
        - dynamodb:PutItem
      Resource:
        Fn::GetAtt:
          - ConnectionsTable
          - Arn

functions:
  authorizer:
    handler: src/authorizer.handler
  broadcast:
    handler: src/broadcast.handler
  websocket:
    handler: src/websocket.handler
    events:
      - websocket:
          route: $connect
          authorizer:
            name: authorizer
            identitySource:
              - 'route.request.header.X-Forwarded-Proto'

      - websocket:
          # Route messages here if '$request.body.action' is 'routeA'.
          # You can adjust which property to use for routing by adjusting
          # 'websocketsApiRouteSelectionExpression'.
          route: routeA
      - websocket:
          route: $default
      - websocket:
          route: $disconnect

resources:
  Resources:
    ConnectionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        SSESpecification:
          SSEEnabled: true
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true

